# Generated by Django 5.1.2 on 2024-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_face_encoding_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
