# Generated by Django 5.1.2 on 2025-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post_likes_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_face_login_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
