# Generated by Django 5.1 on 2025-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_faces/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
